package co.com.ceiba.estacionamiento.julian.henao.functionalTest.StepDefinition;

import static org.junit.Assert.assertTrue;

import java.util.concurrent.TimeUnit;

import org.junit.After;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import co.com.ceiba.estacionamiento.julian.henao.pageObjects.IngresarVehiculo;
import cucumber.api.java.Before;
import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;
import cucumber.api.java.en.When;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class PasoCrearVehiculo {

	private static WebDriver driver;
	private IngresarVehiculo ingresarVehiculo;
	
	@Before
	public void setUp(){
		System.setProperty("webdriver.chrome.driver", "C:\\chromedriver.exe");
		driver = new ChromeDriver();
		ingresarVehiculo = new IngresarVehiculo(driver);
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
	}
	
	@After
	public void cleanUp(){
		driver.manage().deleteAllCookies();
		driver.close();
	}	
	
	@Given("the user is on the page vehicules")
	public void user_on_page_to_create_vehicule() {
		System.out.println("the user is on the page vehicules");
		// Navegar a la pagina
		driver.get("localhost:8080/#/registrarVehiculo");
	}

	@When("the user enters car plate and choose automovil")
	public void user_enters_car_plate_and_choose_automovil() {
		
		System.out.println("Usuario ingresando placa y escogiendo automovil");
						
		String placa = placaAleatoria();
		String tipoVehiculo = "Automovil";		
		
		ingresarVehiculo.ingresarPlaca(placa);
		System.out.println("Placa: "+ placa);
		ingresarVehiculo.seleccionarTipoVehiculo(tipoVehiculo);
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		System.out.println(" Tipo de Vehiculo: "+ tipoVehiculo );
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		ingresarVehiculo.botonIngresarVehiculo();	
	}

	@Then("the user should be able to enter vehicule")
	public void user_should_see_account_balance() {
		System.out.println("Usuario ve mensaje ingreso satisfactorio de vehiculo");
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);	
		String mensajeExitoso = ingresarVehiculo.getMensajeExito();
		System.out.println(mensajeExitoso);
		assertTrue(mensajeExitoso.contains("Vehiculo Ingresado exitosamente"));
	}

	/*
	 * @When("the user enters bad credentials") public void
	 * user_enter_bad_credentials(){
	 * driver.findElement(By.id("MainContent_txtUserName")).sendKeys(
	 * "trim@testemail.com");
	 * driver.findElement(By.id("MainContent_txtPassword")).sendKeys("tarpass");
	 * driver.findElement(By.id("MainContent_btnLogin")).click(); }
	 * 
	 * @Then("the user should not be able to login") public void
	 * user_should_not_login(){ System.out.println("Usuario no pudo ingresar");
	 * }
	 */

	/// Placa:
	/// /html/body/app-root/app-registrarvehiculo/div/form/div[1]/div/app-campoerror/div/div
	/// " Por favor ingrese la placa. Solo letras y números [a-z,A-Z,0-9] "

	/// Cilindraje:
	/// /html/body/app-root/app-registrarvehiculo/div/form/div[3]/div/app-campoerror/div/div
	/// " Por favor ingrese un cilindraje mayor a cero para la moto "

	// PLACAIngresa ya se encuentra en el parqueadero
	// /html/body/app-root/app-registrarvehiculo/div/form/div[1]
	// " El vehiculo con la PLACA ingresada se encuentra en el parqueadero y NO
	// ha salido "
	
	public String placaAleatoria(){
		String alfabeto = "bcdefghijklmnopqrstuvwxyz";
	    String placa = "";
		for (int i = 0; i < 3; i++) {
	        placa = placa + alfabeto.charAt((int) (Math.random()*alfabeto.length()));
	    }
	    int num = (int) (Math.random()*1000);		
		return placa.toUpperCase() + "" + num;
	}
}
